# Chapter 13 연습문제

In [2]:
#1. 길이가 10인 0-백터를 만드세요.
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2. 길이가 10이며 다섯번재 원소만 1이고 나머지 원소는 모두 0인 백터를 만드세요.

data = np.zeros(10)
data[4] = 1
print(data)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [50]:
# 3. 10부터 49까지의 값을 가지는 백터를 만드세요.

data = np.arange(10, 50)
print(data)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [57]:
# 4. 위(3번) 백터의 순서를 바꾸세요.

np.sort(data)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [6]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

data = np.arange(0, 9).reshape(1,3,3)
print(data)


[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [7]:
# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

data = np.array([1,2,0,0,4,0])
a = data>0
data[a]

array([1, 2, 4])

In [70]:
# 7. 3x3 단위 행렬(identity matrix)을 만드세요

data = np.identity(n=3, dtype=np.int8)
print(data)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [77]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요
np.random.seed(1000)
#a = np.random.randn(9).reshape(3,3)
a= np.random.randint(1,100,(3, 3), dtype=int)
data = np.array(a)
print(data)

[[52 88 72]
 [65 95 93]
 [ 2 62  1]]


In [78]:
# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.
max = data.max()
min = data.min()
print(max)
print(min)

95
1


In [79]:
# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
#test_array.mean(axis=1)

v_sum = data.sum(axis=0)
v_avg = v_sum.mean()
print(v_avg)

h_sum = data.sum(axis=1)
h_avg =h_sum.mean()
print(h_avg)

176.66666666666666
176.66666666666666
